// packages/vue/example/ASCII.vue
<script setup lang="ts">
import { measureText } from "@opentui/core"
import { ref, computed } from "vue"

const text = "ASCII"
const font = ref<"block" | "shade" | "slick" | "tiny">("tiny")

const dimensions = computed(() => {
  return measureText({
    text,
    font: font.value,
  })
})

const handleFontChange = (_: any, option: any) => {
  font.value = option?.value
}

const selectOptions = [
  {
    name: "Tiny",
    description: "Tiny font",
    value: "tiny",
  },
  {
    name: "Block",
    description: "Block font",
    value: "block",
  },
  {
    name: "Slick",
    description: "Slick font",
    value: "slick",
  },
  {
    name: "Shade",
    description: "Shade font",
    value: "shade",
  },
]

const groupStyles = { paddingLeft: 1, paddingRight: 1 }
const boxStyles = { height: 8, marginBottom: 1 }
const selectStyles = { flexGrow: 1 }
</script>

<template>
  <boxRenderable :style="groupStyles">
    <boxRenderable :style="boxStyles">
      <selectRenderable
        :focused="true"
        showScrollIndicator
        :onChange="handleFontChange"
        :options="selectOptions"
        :style="selectStyles"
      ></selectRenderable>
    </boxRenderable>
    <asciiFontRenderable :style="{ width: dimensions.width, height: dimensions.height }" :text="text" :font="font" />
  </boxRenderable>
</template>

// packages/react/examples/ascii.tsx
import { measureText } from "@opentui/core"
import { render } from "@opentui/react"
import { useState } from "react"

export const App = () => {
  const text = "ASCII"
  const [font, setFont] = useState<"block" | "shade" | "slick" | "tiny">("tiny")

  const { width, height } = measureText({
    text,
    font,
  })

  return (
    <group style={{ paddingLeft: 1, paddingRight: 1 }}>
      <box
        style={{
          height: 8,
          marginBottom: 1,
        }}
      >
        <select
          focused
          onChange={(_, option) => setFont(option?.value)}
          showScrollIndicator
          options={[
            {
              name: "Tiny",
              description: "Tiny font",
              value: "tiny",
            },
            {
              name: "Block",
              description: "Block font",
              value: "block",
            },
            {
              name: "Slick",
              description: "Slick font",
              value: "slick",
            },
            {
              name: "Shade",
              description: "Shade font",
              value: "shade",
            },
          ]}
          style={{ flexGrow: 1 }}
        />
      </box>

      <ascii-font style={{ width, height }} text={text} font={font} />
    </group>
  )
}

render(<App />)
